// angular-web-freemi/src/app/app.component.ts
import {AfterViewInit, Component, ElementRef, ViewChild} from '@angular/core';

interface ReactData {
  message: string;
  data?: any;
  appName: string;
}

const isReactData = (data?: object): data is ReactData => data && data.hasOwnProperty('appName') && data.hasOwnProperty('message');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {
  dataToSend: string;
  reactData: string;

  @ViewChild('freem') myIframe: ElementRef;

  sendToReact() {
    this.myIframe.nativeElement.contentWindow.postMessage(this.dataToSend, '*');
  }

  ngAfterViewInit(): void {
    window.onmessage = e => {
      const data = e.data;
      if (isReactData(data)) {
        console.log('data', data);
        this.reactData = data.message;
      }
    };
  }
}

<input [(ngModel)]="dataToSend"/>
<button (click)="sendToReact()">Send to react</button>
<span>{{reactData}}</span><br/>
<iframe #freem src="http://localhost:3000"></iframe>

// react-freemi/src/App.tsx
import React, {useEffect, useState} from 'react';
import './App.css';

type ReactData = {
    message: string;
    data?: any;
    appName: string;
}

const sendToParentApp = (data: ReactData) => {
    window.top.postMessage(data, '*');
};

const App = () => {
    const [messageReceived, setMessageReceived] = useState("");
    const [dataToSend, setDataToSend] = useState();
    useEffect(() => {
        window.onmessage = (e: MessageEvent) => {
            if (e.data) {
                setMessageReceived(e.data)
            }
        };
    }, []);

    const sendData = () => {
        sendToParentApp({appName: "react-app", message: dataToSend})
    };

    return (
        <div className="App">
            <p>
                {messageReceived}
            </p>
            <input onChange={(e) => setDataToSend(e.target.value)}/>
            <button onClick={sendData}>Send to angular</button>
        </div>
    );
};

export default App;
